#to create the containers locally from the Dockerfiles from
#version: '3'
#
#services:
#  frontend:
#    build: ./client
#    ports:
#      - "3000:3000"
#  api:
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ppldb
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#    build:
#      context: .
#      dockerfile: Dockerfile
#  db:
#    build:  ./dbDocker
#    restart: always
#    ports:
#      - "5431:5432"
#volumes:
#  postgres-data:



#to create the containers locally from my personal repository
version: '3'

services:
  frontend:
    image: ronksks/usercrud-frontend:latest
    ports:
      - "3000:3000"
  api:
    image: ronksks/usercrud-api:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ppldb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image:  ronksks/usercrud-db:latest
    restart: always
    environment:
      - POSTGRES_DB=ppldb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5430:5432"
