#version: '3'
#services:
#  frontend:
#    build: ./client
#    ports:
#      - "3000:3000"
#  api:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ppldb
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#  db:
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_DB=ppldb
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#
#volumes:
#  postgres-data:
version: '3'

services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
  api:
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ppldb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    build:
      context: .
      dockerfile: Dockerfile
  db:
    build:  ./dbDocker
    restart: always
    ports:
      - "5431:5432"
volumes:
  postgres-data:
